# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scout_scout}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jesse Newland"]
  s.date = %q{2010-07-15}
  s.description = %q{API wrapper for scout.com}
  s.email = %q{jnewland@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/scout_scout.rb",
     "lib/scout_scout/alert.rb",
     "lib/scout_scout/cluster.rb",
     "lib/scout_scout/descriptor.rb",
     "lib/scout_scout/metric.rb",
     "lib/scout_scout/person.rb",
     "lib/scout_scout/plugin.rb",
     "lib/scout_scout/server.rb",
     "lib/scout_scout/trigger.rb",
     "lib/scout_scout/version.rb",
     "spec/fixtures/activities.xml",
     "spec/fixtures/client.xml",
     "spec/fixtures/client_by_hostname.xml",
     "spec/fixtures/clients.xml",
     "spec/fixtures/data.xml",
     "spec/fixtures/descriptors.xml",
     "spec/fixtures/plugin_data.xml",
     "spec/fixtures/plugins.xml",
     "spec/fixtures/triggers.xml",
     "spec/scout_scout_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jnewland/scout_scout}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{API wrapper for scout.com}
  s.test_files = [
    "spec/scout_scout_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, ["~> 0.1.8"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.5.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
      s.add_dependency(%q<hashie>, ["~> 0.1.8"])
      s.add_dependency(%q<httparty>, ["~> 0.5.0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
    s.add_dependency(%q<hashie>, ["~> 0.1.8"])
    s.add_dependency(%q<httparty>, ["~> 0.5.0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

